services:
  fastapi:
    image: python:3.13.2
    container_name: ih-fastapi
    restart: always
    networks:
      - ishigami-hills
      - reverse-proxy-internal
    labels:
      - traefik.enable=true
      - traefik.http.routers.ih-fastapi.entrypoints=http
      - traefik.http.routers.ih-fastapi.rule=Host(`${FAST_API_HOST}`)
      - traefik.http.routers.ih-fastapi.service=ih-fastapi
      - traefik.http.services.ih-fastapi.loadbalancer.server.port=8000
    volumes:
      - ./volume/ishigami-hills:/ishigami-hills
      - /usr/share/zoneinfo/Asia/Tokyo:/etc/localtime:ro
    command: bash -c "pip3 install -r requirements.txt --break-system-packages && uvicorn main:app --host 0.0.0.0"
    tty: true
    working_dir: /ishigami-hills

networks:
  ishigami-hills:
    name: ishigami-hills
  reverse-proxy-internal:
    external: true
