services:
  api:
    image: python:3.13.2
    container_name: ishigami-hills-api
    restart: always
    networks:
      - ishigami-hills
      - reverse-proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.ishigami-hills-api.entrypoints=http
      - traefik.http.routers.ishigami-hills-api.rule=Host(`${FAST_API_HOST}`)
      - traefik.http.routers.ishigami-hills-api.service=ishigami-hills-api
      - traefik.http.services.ishigami-hills-api.loadbalancer.server.port=${FAST_API_PORT}
    volumes:
      - ./volume/ishigami-hills:/ishigami-hills
      - /usr/share/zoneinfo/Asia/Tokyo:/etc/localtime:ro
    command: bash -c "pip3 install -r requirements.txt --break-system-packages && uvicorn main:app --host 0.0.0.0"
    tty: true
    working_dir: /ishigami-hills

networks:
  ishigami-hills:
    name: ishigami-hills
  reverse-proxy:
    external: true
