name: Local Assistant
version: 1.0.0
schema: v1
models:
  - name: gemma3:4b
    provider: ollama
    model: gemma3:4b
    roles:
      - chat
      - embed
      - rerank
      - edit
      - apply
      - summarize
context:
  - provider: file
  - provider: code
  - provider: diff
  - provider: currentFile
  - provider: terminal
  - provider: docs
  - provider: open
  - provider: web
  - provider: codebase
  - provider: folder
  - provider: search
  - provider: url
  - provider: clipboard
  - provider: tree
  - provider: problems
  - provider: debugger
  - provider: repo-map
  - provider: os
