services:
  fastapi:
    networks:
      - reverse-proxy-internal
    labels:
      - traefik.enable=true
      - traefik.http.routers.ih-fastapi.entrypoints=http
      - traefik.http.routers.ih-fastapi.rule=Host(`${FAST_API_HOST}`)
      - traefik.http.routers.ih-fastapi.service=ih-fastapi
      - traefik.http.services.ih-fastapi.loadbalancer.server.port=8000
    command: bash script/run_production_server.sh

networks:
  reverse-proxy-internal:
    external: true
