services:
  fastapi:
    image: python:3.13.2
    container_name: ih-fastapi
    restart: always
    networks:
      - ishigami-hills
    ports:
      - 8000:8000
    volumes:
      - ./volume/api/ishigami-hills:/ishigami-hills
      - /usr/share/zoneinfo/Asia/Tokyo:/etc/localtime:ro
    command: bash script/run_dev_server.sh
    tty: true
    working_dir: /ishigami-hills

networks:
  ishigami-hills:
    name: ishigami-hills
