defaultContentLanguage: ja
ennableEmoji: true
enableGitInfo: true
enableRobotsTXT: true
frontmatter:
  date:
    - :git
  lastmod:
    - :git
  publishDate:
    - :git
hasCJKLanguage: true
languageCode: ja
outputs:
  home:
    - HTML
    - JSON
    - RSS
theme: blowfish
timeZone: Asia/Tokyo
title: 石上ヒルズ
