/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/rss/general-information": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * General Information
         * @description 公式サイトの一般情報を取得する。
         */
        get: operations["General_Information_rss_general_information_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rss/gotch-note": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Gotch Note
         * @description GotchのNoteを取得する。
         */
        get: operations["Gotch_Note_rss_gotch_note_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rss/avms-note": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Avms Note
         * @description AVMSのNoteを取得する。
         */
        get: operations["AVMS_Note_rss_avms_note_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Feed */
        Feed: {
            /** Url */
            url: string;
            /** Title */
            title: string;
            /** Link */
            link: string;
            /** Author */
            author: string;
            /** Description */
            description: string;
            /** Image */
            image: string;
        };
        /** Item */
        Item: {
            /** Title */
            title: string;
            /** Pubdate */
            pubDate: string;
            /** Link */
            link: string;
            /** Guid */
            guid: string;
            /** Author */
            author: string;
            /** Thumbnail */
            thumbnail: string;
            /** Description */
            description: string;
            /** Content */
            content: string;
            /** Enclosure */
            enclosure: Record<string, never>;
            /** Categories */
            categories: unknown[];
        };
        /** RSS */
        RSS: {
            /** Status */
            status: string;
            feed: components["schemas"]["Feed"];
            /** Items */
            items: components["schemas"]["Item"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    General_Information_rss_general_information_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RSS"];
                };
            };
        };
    };
    Gotch_Note_rss_gotch_note_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RSS"];
                };
            };
        };
    };
    AVMS_Note_rss_avms_note_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RSS"];
                };
            };
        };
    };
}
