name: Deploy Fansite
on:
  workflow_dispatch:
  push:
    branches:
    - work

jobs:
  # Source job
  source:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout Fansite
      uses: actions/checkout@v4
    # - name: Enable Corepack
    #   run: corepack enable
    - name: Setup Node.js
      uses: actions/setup-node@v4
  # Build job
  build:
    runs-on: ubuntu-24.04
    needs: source
    steps:
    - name: Install Packages
      run: npm install
    - name: Build Fansite
      run: NUXT_APP_BASE_URL=/ishigami-hills/ npm run generate --preset github_pages
    - name: Upload Artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: github_pages/.output/public
  # Deploy job
  deploy:
    runs-on: ubuntu-24.04
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github_pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
    - name: Deploy Fansite
      id: deploy
      uses: actions/deploy-pages@v4
