name: Deploy Fansite
on:
  workflow_dispatch:
  push:
    branches:
    - work
    paths:
    - .github/workflows/deploy-fansite.yml
    - assets/**
    - public/**
    - server/**
    - app.vue
    - biome.json
    - nuxt.config.ts
    - package.json
    - package-lock.json
    - tailwind.config.js
    - tsconfig.json

jobs:
  # Build job
  build:
    runs-on: ubuntu-24.04
    env:
      TZ: Asia/Tokyo
    steps:
    - name: Checkout Fansite
      uses: actions/checkout@v4
    # - name: Enable Corepack
    #   run: corepack enable
    - name: Setup Node.js
      uses: actions/setup-node@v4
    - name: Install Packages
      run: npm install
    - name: Build Fansite
      run: npm run generate
    - name: Upload Artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: dist
  # Deploy job
  deploy:
    runs-on: ubuntu-24.04
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github_pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
    - name: Deploy Fansite
      id: deploy
      uses: actions/deploy-pages@v4
