# Site
title: 石上ヒルズ
subtitle: 後藤正文になる
description: 波の向こうの空の向こうまで
author: Kotaro Kuroda
language: ja
timezone: Asia/Tokyo

# URL
url: https://zen96k.github.io/ishigami-hills
pretty_urls:
  trailing_index: false
  trailing_html: false

# Directory

# Writing

# Home page setting

# Category & Tag

# Metadata elements
meta_generator: true

# Date / Time format

# Pagination

# Include / Exclude file(s)

# Extensions
theme: butterfly
